# Install environment for dev
#
# Create image :
# VERSION 1.0

FROM ubuntu:latest
MAINTAINER Maxime Raynal - <me@maxproject.fr>

#EXPOSE 80:8081

# Make sure the package repository is up to date
ADD sources.list /etc/apt/sources.list
RUN apt-get -y update

# Install prerequirement
RUN apt-get install -y python3.4 python3-pip --force-yes --fix-missing

RUN ln -s /usr/bin/python3.4 /usr/bin/python

RUN python -m easy_install pip

RUN python -m pip install Django

RUN mkdir /var/www/

ADD setup.sh /root/setup.sh
RUN chmod u+x /root/setup.sh

ENTRYPOINT ["/root/setup.sh"]
